### PR TITLE
Vote on prefix-only core modules

### PR DESCRIPTION
**Pull request by aduh95**
The voting options were presented in a private email instead of a public issue due the tight schedule, as we want to have a resolution before Node.js v18.x semver cutoff which is next week.

Use one of the following methods to case a vote (or abstain):

<details><summary>Vote using <code>npx</code>+<code>gh</code> (requires Node.js 16+, and git)</summary>

Requires [`gh`](https://cli.github.com) (GitHub CLI tool) to be installed, and logged in to your GitHub account.

```sh
npx --package=@aduh95/caritat voteOnGitHub https://github.com/nodejs/TSC/pull/1206
```

If you want to abstain, you can use the `--abstain` flag (it will create a ballot with all the scores set to 0):

```sh
npx --package=@aduh95/caritat voteOnGitHub https://github.com/nodejs/TSC/pull/1206 --abstain
```

</details>

<details><summary>Vote using <code>npx</code> (requires Node.js 16+, and git)</summary>

```sh
# Cloning and pushing using SSH
npx --package=@aduh95/caritat voteUsingGit -r git@github.com:nodejs/TSC.git \
  -b vote-prefix-only-core-modules -p votes/prefix-only-core-modules

# Cloning and pushing using HTTPS
USERNAME=<your-github-handle> \
npx --package=@aduh95/caritat voteUsingGit -r https://$USERNAME@github.com/nodejs/TSC.git \
  -b vote-prefix-only-core-modules -p votes/prefix-only-core-modules --handle "$USERNAME"

# To abstain, use the flag --abstain
npx --package=@aduh95/caritat voteUsingGit -r git@github.com:nodejs/TSC.git \
  -b vote-prefix-only-core-modules -p votes/prefix-only-core-modules --abstain
```

</details>

<details><summary>Vote using <code>sh</code> (requires git, and OpenSSL CLI)</summary>

Caution: LibreSSL CLI is not compatible, please use OpenSSL 1.1.1+.

```sh
curl -LOJ https://github.com/stduhpf/caritat/raw/HEAD/sh/voteUsingGit.sh
curl -LOJ https://github.com/stduhpf/caritat/raw/HEAD/sh/encryptBallot.sh
chmod +x encryptBallot.sh
sh ./voteUsingGit.sh \
  <your-github-handle> \
  git@github.com:nodejs/TSC.git \
  vote-prefix-only-core-modules \
  votes/prefix-only-core-modules
rm encryptBallot.sh
rm voteUsingGit.sh
```

</details>

<details><summary>Vote using PowerShell (requires git, and OpenSSL CLI)</summary>

Caution: LibreSSL CLI is not compatible, please use OpenSSL 1.1.1+.

```sh
Set-ExecutionPolicy Bypass -Scope Process -Force
[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
$tmpFile = $(New-TemporaryFile | Rename-Item -NewName { $_ -replace 'tmp$', 'ps1'} -PassThru)
$encryptBallot = $tmpFile -replace '\\[^\\]+$','\encryptBallot.ps1'
((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/stduhpf/caritat/HEAD/sh/voteUsingGit.ps1')) | Out-File -FilePath $tmpFile
((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/stduhpf/caritat/HEAD/sh/encryptBallot.ps1')) | Out-File -FilePath $encryptBallot
& $tmpFile `
  <your-github-handle> `
  git@github.com:nodejs/TSC.git `
  vote-prefix-only-core-modules `
  votes/prefix-only-core-modules
Remove-Item $encryptBallot
Remove-Item $tmpFile
```

</details>

<details><summary>Vote using the web</summary>

1. Fill in the ballot at <https://stduhpf.github.io/caritat/#https://github.com/nodejs/TSC/pull/1206>. It will copy the encrypted ballot to your clipboard.
2. Paste the encrypted ballot in <https://github.com/nodejs/TSC/new/vote-prefix-only-core-modules/votes/prefix-only-core-modules>. It's recommended to use `<your-github-handle>.json` for the file name.
3. Commit directly to the `vote-prefix-only-core-modules` branch.

To abstain, set all scores to `0` before encrypting the ballot.

</details>

This will encrypt a file containing your preferences, file that will be decrypted when doing the counting this week-end, Monday at the latest.

The counting will be done using the Condorcet method.

_I didn't spend much time on improving the vote tools since last time, sorry for the inconvenience._

### CODE REVIEW

**Comment by apapirovski** [comment]
Might be worth updating the instructions for future iterations to include the note about this being high-to-low scoring, rather than the reverse. It's not immediately obvious.

**Comment by Trott** [comment]
It seems like https://github.com/nodejs/TSC/pull/1208 was supposed to end up as part of this pull request but somehow ended up as a separate one. @jasnell @aduh95

**Comment by ljharb** [comment]
What does it mean that there's two winners? Is another vote needed to choose between them?

**Comment by ljharb** [comment]
So we're ok with users expecting `node:foo` and `foo` to be the same thing, but `node:test` and `test` not to be?

**Review by joyeecheung — APPROVED** [review]

**Comment by Trott** [comment]
The Charter says:

> For all votes, a simple majority of all TSC members for, or against, the issue wins. A TSC member may choose to participate in any vote through abstention.

So we should be able to have (hopefully again, very quick) yes-or-no vote on the winner and make sure that at least 11 members (or whatever number of members is a majority once you account for explicit abstentions) are in favor of the 

If the system is working as intended, then this should pass without a problem. If it doesn't, then that may indicate a problem with the voting system. (We may, for example, need to require all members to participate for the condorcet system to work within the charter guidelines.)

I'm bringing this up because the vote was close. We don't normally have a close vote on anything, so this isn't usually an issue.

**Comment by Trott** [comment]
> please react to this comment to vote on the following proposal: Ship the test runner as `node:test` and `require('test')` loads from userland.

(We don't have any reason to believe that the owner of the test module on npm would be happy to hand over the package name to us, right? That could change my abstain to a yes if we could be sure that anyone doing `npm install test` gets something that directs them to please not do that or something like that.)

**Comment by ljharb** [comment]
@Trott we also don't have any reason to believe they wouldn't - i think out of about 50 such requests over the last decade, i've only ever had 2-3 turn me down. @gozala - any chance you'd be willing to do that?

**Comment by Trott** [comment]
As I write this, there are 7 TSC votes in favor, 1 against, and 4 abstentions on the [finalizing vote comment](https://github.com/nodejs/TSC/pull/1206#issuecomment-1096855085). We need at least 2 more TSC folks to participate, possibly more, to come to a resolution. I can't make the TSC meeting today, but if folks who are there could remind anyone there who hasn't voted yet, that would be helpful.

**Comment by Trott** [comment]
> As I write this, there are 7 TSC votes in favor, 1 against, and 4 abstentions on the [finalizing vote comment](https://github.com/nodejs/TSC/pull/1206#issuecomment-1096855085). We need at least 2 more TSC folks to participate, possibly more, to come to a resolution. I can't make the TSC meeting today, but if folks who are there could remind anyone there who hasn't voted yet, that would be helpful.

One more abstention or yes vote from a @nodejs/tsc member will bring the vote to a close in conformance with our charter.

**Comment by ChALkeR** [comment]
I think that happened now ).

**Comment by Gozala** [comment]
> @Trott we also don't have any reason to believe they wouldn't - i think out of about 50 such requests over the last decade, i've only ever had 2-3 turn me down. @Gozala - any chance you'd be willing to do that?

@ljharb Are you asking if I'm willing to hand over the 'test' package to the node core ? If so, I would not mind doing that. If it is a different ask please provide some more info as I lack context.

That said I would much rather see prefixed node modules however as more conflicts undoubtedly would occur over time.

**Comment by ljharb** [comment]
@Gozala yep, that's what i was asking! I'm pleased to hear you'd be open to it.

**Review by mhdawson — APPROVED** [review]
LGTM

**Review by Trott — APPROVED** [review]

**Pull request merged**
