### PR TITLE
meta: remove MylesBorins from TSC membership list

### PR DESCRIPTION
**Pull request by MylesBorins**
Refs: https://medium.com/@mylesborins/effective-immediately-i-am-stepping-down-from-the-nodejs-tsc-3df37c6ccbae

### CODE REVIEW

**Comment by Trott** [comment]
Probably not for this PR, but I would recommend alphabetizing the two lists by GitHub handles or otherwise ordering them in a fashion that doesn't imply that some people are more senior than others. As I understand it, the TSC is intended to be organized as a committee of equals.

**Comment by MylesBorins** [comment]
I thought it was alphabetized 
¯\\\_(ツ)\_/¯

**Comment by mathiasbynens** [comment]
> I thought it was alphabetized

The “emeritus members” list is, but the “current members” list isn’t.

**Comment by Dracooooo** [comment]
@MylesBorins Hi, can you please refrain from using ¯\_(ツ)_/¯ in the future? I know it looks cool as an emoji, but as a Japanese person, I feel offended by people using the "tsu" for such things. Thanks in advance.

**Comment by abatishchev** [comment]
@Dracooooo Hi, can you please refrain from correcting random people over the internet in the future? I know it looks cool, but I I feel offended by people being offended by emojis. Thanks in advance.

**Comment by jasnell** [comment]
Both comments are unhelpful and off topic.

**Pull request merged**
