### PR TITLE
decharter website working group

### PR DESCRIPTION
**Pull request by Trott**
The Website working group has not been a functioning working group for
some time. (No meetings, charter is frequently iignored, etc.) It is
effectively a GitHub team and I would like to be able to add and remove
people as appropriate, but I can't do that with a working group. Let's
switch it to a GitHub team. We can always recharter at a later date if
necessary.

### CODE REVIEW

**Comment by richardlau** [comment]
If this goes ahead there's a corresponding list over in https://github.com/nodejs/nodejs.org/blob/master/locale/en/about/working-groups.md.

**Comment by mhdawson** [comment]
FYI @nodejs/website

**Comment by aymen94** [comment]
yes, there's a little bit of a mess.
We have to organize at least one meeting every 2 weeks.

**Comment by Trott** [comment]
If I can get two more approvals from @nodejs/tsc, that would unequivocally meet the requirements in our docs for dechartering. If you don't want to weigh in on this at all, explicit abstentions help too!  @addaleax @apapirovski @ChALkeR @danbev @fhinkel @Fishrock123 @gabrielschulhof @gireeshpunathil @joyeecheung @thefourtheye @tniessen

**Pull request merged**
