### PR TITLE
Open communications should be a priority

### PR DESCRIPTION
**Pull request by koresar**
As per discussion with some members of the board here https://github.com/nodejs/board/issues/70#issuecomment-328195328 I would like to suggest the following change to the **Guiding Principle** as proposed by @williamkapke.

Let's copy the best.

### CODE REVIEW

**Comment by koresar** [comment]
Could you please propose the place where this would be more suitable?

**Comment by jasnell** [comment]
The expectations doc being worked on in the admin repo would likely be more appropriate

**Comment by koresar** [comment]
Huh. Funny. That's what my change is about. Open (not for writing maybe)
any communication. Including the "admin" and all the other closed repos.

**Comment by MylesBorins** [comment]
The admin repo is an open repo. The only closed repos in the org is
moderation and security

**Comment by koresar** [comment]
I see. Thank you for the info. I've just found the repo.
Do you think it's reasonable to move this PR change to this file?
https://github.com/nodejs/TSC/blob/master/CODE_OF_CONDUCT.md

**Comment by bnb** [comment]
As @jasnell said, I think the https://github.com/nodejs/admin repo is an entirely appropriate place. I don't think the CoC is an appropriate place for discussion which medium of communications we use, as it will detract from the other parts of the message in that doc.

**Comment by mhdawson** [comment]
I suggest you take the content of this PR, and submit it as a document titled "Communications-policy.md" in the admin repo (https://github.com/nodejs/admin/pull/12).  I'm also happy to do that if you'd prefer.

**Comment by koresar** [comment]
That's neat suggestion. Please don't waste your time please. Let me do it.

Thank you for the help.

**Comment by MylesBorins** [comment]
@koresar I'm going to go ahead and close this as it does not appear to be actionable in the current state. Please lmk if you want support with anything in the future

**Pull request closed without merging**
