### PR TITLE
General update to the Member Travel Fund doc

### PR DESCRIPTION
**Pull request by addaleax**
We talked about travel funding at the last TSC meeting with the result that the document on it should be updated and we would want to keep track of all approved requests (and, in particular, their amounts) in a table.

@nodejs/tsc Please take a look and let me know what you think!

### CODE REVIEW

**Comment by williamkapke** [comment]
This was discussed in the 2016-12-15 TSC meeting here:
https://www.youtube.com/watch?v=r1chJO9nbRQ&t=2090s

**Comment by williamkapke** [comment]
This should fix #145

**Comment by addaleax** [comment]
> This should fix #145

Added a `Fixes:` tag to the commit message, thanks for pointing that out!

**Comment by mikeal** [comment]
I don't know if this needs to be in the doc but in the case where we don't provide a stipend but instead do a re-imbursement or book the travel ourselves we should update the doc with the real cost.

**Comment by addaleax** [comment]
@mikeal Sorry for the late reply – I guess that depends on who’s doing the update. I assume you wouldn’t want to take that work on for yourself, but otoh I think in the cases where travel is directly booked by the NF the person in question doesn’t even know the total amount? (I don’t know how much my flight to Austin was, for example.)

**Comment by addaleax** [comment]
I probably won’t be able to be at tomorrow’s TSC meeting, so just to let everyone know:
- I haven’t merged this PR yet because I’d kinda prefer if a TSC member merged this
- I don’t think this is urgent, so feel free to wait on @mikeal’s response to my last comment

**Comment by Fishrock123** [comment]
@addaleax so @mikeal on call today said we can just get that info from the foundation (such as from @mikeal).

Could you update the doc with info stating that one travel is done we should open a PR against the repo to adjust it to the actual cost (including any costs we may need to get from the NF)?

**Comment by Fishrock123** [comment]
@nodejs/tsc Will be merging this once @addaleax updates it if there are no outstanding concerns.

**Comment by addaleax** [comment]
@Fishrock123 done, added a short note on that. if you prefer some other wording let me know, or just edit this PR :)

**Comment by Fishrock123** [comment]
TSC has been consistently positive about this, landing as we all appear to have consensus about this.

Landed in https://github.com/nodejs/TSC/commit/6ea0b676e1e7cc3d9587b9aa3cc26ebf8dcb4f50, thanks again @addaleax!

**Pull request closed without merging**
