### PR TITLE
meta: remove nebrius from TSC membership list

### PR DESCRIPTION
**Pull request by nebrius**

### CODE REVIEW

**Comment by nebrius** [comment]
related: https://github.com/nodejs/email/pull/49

**Comment by Trott** [comment]
Maybe consider moving yourself to Emeritus instead of deleting? Same for @addaleax? Up to each of you individually, of course.

**Comment by addaleax** [comment]
I’m fine with either

**Comment by nebrius** [comment]
> Maybe consider moving yourself to Emeritus instead of deleting? Same for @addaleax? Up to each of you individually, of course.

Let me think about this, I'll get back to you soon.

**Comment by nebrius** [comment]
After thinking about it, yes I do want to be moved to emeritus. I'll make the change. @addaleax would you like me to add you to the emeritus list as part of this PR?

**Comment by addaleax** [comment]
@nebrius go ahead, if only for the increased transparency

**Comment by nebrius** [comment]
Done. FYI I reordered the emeritus section to be alphabetical by first name to match the current list of members.

**Pull request merged**
