### PR TITLE
Moderation Policy: no bots but our bots

### PR DESCRIPTION
**Pull request by Trott**
ping @nodejs/tsc @nodejs/moderation

### CODE REVIEW

**Comment by MylesBorins** [comment]
@Trott we may want to do this in the admin repo

The Moderation doc is living in two places. We likely should move this doc over there first

**Comment by vsemozhetbyt** [comment]
Refs: https://github.com/nodejs/moderation/issues/155

**Comment by othiym23** [comment]
@MylesBorins It's [already there](https://github.com/nodejs/admin/commit/527334725aa66e9c6b218239047a8152c199afeb) (I only figured that out on Friday myself, don't feel bad). @Trott -- you want to close this and move the proposal there? And should we start the process of removing the moderation policy here? It's at best confusing having it in two places, even if one of them is a deprecated repository.

**Comment by othiym23** [comment]
Also, on the proposal's merits: I think this is a sensible proposal, and also would be interested in basically codifying a "quick to ban, quick to forgive" policy around bots or any other behavior that can rapidly trigger events in repos, because it's so easy for bot-like activity to create a lot of work for a lot of people.

**Comment by MylesBorins** [comment]
I've opened https://github.com/nodejs/TSC/pull/395

**Comment by MylesBorins** [comment]
This is going to have to be moved to the admin repo

**Comment by Trott** [comment]
> This is going to have to be moved to the admin repo.

https://github.com/nodejs/admin/pull/31

**Pull request closed without merging**
