### PR TITLE
Add @nebrius as a member of the TSC

### PR DESCRIPTION
**Pull request by williamkapke**
I'll start by saying: I probably missed something. 😕 

I know @nebrius was [nominated](https://github.com/nodejs/inclusivity/issues/78) by the @nodejs/inclusivity WG as their rep on the TSC... but he didn't officially make it to the TSC? I can't tell.

He started attending TSC meetings as an observer: #57
Then as the nominee: #61
Since he is just has been listed without `(TSC)` after his name: #69

He is also not part of @nodejs/tsc team.

If this is just needing a PR... well here ya go!

### CODE REVIEW

**Comment by rvagg** [comment]
Yes, what you're missing is that I'd expressed a preference to hold off on membership changes to the TSC until we figure out what this group is even for. That process includes trying to make progress on the mission statement, which needs a definition of "node core", then ensuring that the relationship with the board is crystal clear so we know our boundaries, then after that, figuring out what it means to have separate TSC and CTC bodies: what is the nature of the relationship, how do they serve each other, what is there beyond "core" that the TSC might need to care about and how does the TSC fit into that picture in ways that the CTC doesn't? And do we even need a separate TSC or are we just overcomplicating things?

I hope that explains why I've been hesitant to support membership changes, it's nothing about individuals involved by any means, I just don't want to go down a path of entrenching governance bodies that don't have clarity around the reasons for which they exist!

Having said that, @nebrius has been great to have on board and has been very constructive at this level and it's not cool that we started the process of getting an Inclusivity rep on board but never took it to the next step of having a formal vote to make them a TSC member. So let's see if we can get something close to a quorum to have a vote and make it stick. I'm confident that @nebrius is well placed to help us answer some of the questions that I've laid out above.

**Comment by nebrius** [comment]
Thank you for the vote of confidence @rvagg :)

Yes it's been somewhat annoying that the process was started and then stalled, but I completely understand why so don't worry about it. I'm happy we're moving the process forward, and please let me know if there's anything you need from me on my end.

**Comment by williamkapke** [comment]
Thursday's meeting (#110) did not have enough members present for quorum so @nebrius was unable to be added. The 3 members present were in favor. @rvagg said he would try to solicit votes from the other @nodejs/tsc members offline to move this forward.

**Comment by rvagg** [comment]
We have +1's from James, Alexis, Jeremiah and myself.

@bnoordhuis, @chrisdickinson, @cjihrig, @indutny, @misterdjules, @mscdex, @piscisaureus, @shigeki, @trevnorris you're all still on the TSC, we haven't done anything to the membership other than this vote, see above for reasoning on that. In order to move forward here could you all please consider dropping a vote one way or the other in here? This is for the TSC only, doesn't impact the CTC, which already has diverged in its membership.

**Comment by misterdjules** [comment]
LGTM

**Comment by shigeki** [comment]
I'm +1 and sorry for my late vote.

**Comment by mscdex** [comment]
+1

**Comment by jasnell** [comment]
Still LGTM!

**Pull request merged**
