### PR TITLE
Travel Fund Request: Никита Сковорода, May 2017 Collaborators Summit

### PR DESCRIPTION
**Pull request by ChALkeR**
The amount is not final yet, the exact value may decrease, but the estimated upper bound is €680.

_@mikeal suggested to specify the amount in EUR as both the visa fee and lodging are in EUR_.

I will be travelling from Moscow, Russia.

* Travel tickets are about €230-€360 atm + €16.
* Lodging for 3 nights was €211 (I already booked it).
* Visa fee should be under €90 (not exactly sure which category yet).

I will also probably need an invitation for the travel visa.

### CODE REVIEW

**Comment by ChALkeR** [comment]
@bnoordhuis 
> Who needs to extend the invitation?

I sent an email to @mikeal, I believe that should work.

**Comment by Fishrock123** [comment]
Let's just convert to USD once the number is finalized and the amount is paid.

**Comment by ChALkeR** [comment]
The final amount should be about €580 (the travel tickets were closer to the bottom line of the estimated range).
I will update this PR once I recalculate everything (or will file a new one if this gets merged earlier).

**Comment by ChALkeR** [comment]
I have successfully received the travel visa, btw. =)

**Comment by ChALkeR** [comment]
Updated, the final amount is €573.
 * Travel costs to Berlin were €264.
 * Lodging for 3 nights was €211.
 * Total visa costs were €98.

**Comment by ChALkeR** [comment]
What should be the next step here?

**Comment by addaleax** [comment]
@ChALkeR I think this can just be merged. Did you receive the reimbursement already? If so, do you know the value in US $ and can you update with that?

**Comment by ChALkeR** [comment]
@addaleax 
>  Did you receive the reimbursement already?

No, I don't think so. Whom should I contact on that?

**Comment by addaleax** [comment]
I am not sure I have the link anymore (@mikeal ?), but basically there’s a form that you fill out, and then you sent it together with your receipts to ap@linuxfoundation.org (and cc @mikeal, I think, unless that has changed/is changing?).

**Comment by mikeal** [comment]
You can send any standard "expense reimbursement" form (there are dozens of templates on google for which every document or spreadsheet app you prefer). cc me on it, that will change but it hasn't changed yet :)

**Pull request merged**
