### PR TITLE
doc: de-charter benchmarking WG

### PR DESCRIPTION
**Pull request by mhdawson**
Signed-off-by: Michael Dawson <mdawson@devrus.com>

### CODE REVIEW

**Comment by mhdawson** [comment]
See https://github.com/nodejs/TSC/issues/822 for previous discussion.

**Review by cjihrig — APPROVED** [review]

**Review by BethGriggs — APPROVED** [review]

**Comment by Trott** [comment]
I guess we also will need to decommission https://benchmarking.nodejs.org/ and get rid of the DNS record (or redirect it somewhere)?

And we'll need to update https://nodejs.org/en/about/working-groups/ as well.

**Review by Trott — APPROVED** [review]

**Comment by Trott** [comment]
Oooh, maybe we can finally update the "who to CC" list so that `@nodejs/benchmarking` is people to CC about the benchmarks in core. That's been a small-but-still-real DX issue for years now.

**Review by gireeshpunathil — APPROVED** [review]

**Comment by mhdawson** [comment]
@Trott correct once we have dechartered.

**Review by targos — APPROVED** [review]

**Comment by mhdawson** [comment]
Build issue to cleanup infra https://github.com/nodejs/build/issues/2485
PR to update website: https://github.com/nodejs/nodejs.org/pull/3547

@Trott  I'll leave the update to the team as you seem to have something in mind.

**Pull request merged**
