### PR TITLE
remove misterdjules from TSC members

### PR DESCRIPTION
**Pull request by misterdjules**
Removes @misterdjules from TSC members following his resignation from the
TSC.

### CODE REVIEW

**Comment by williamkapke** [comment]
This doc change looks correct to me.

My standard reminder: This list will need to also be updated on the website...
https://github.com/nodejs/nodejs.org/blob/master/locale/en/foundation/tsc/index.md

**Comment by jasnell** [comment]
Unfortunate LGTM

**Comment by cjihrig** [comment]
Yes, unfortunate LGTM.

**Comment by misterdjules** [comment]
@williamkapke 

> My standard reminder: This list will need to also be updated on the website...
https://github.com/nodejs/nodejs.org/blob/master/locale/en/foundation/tsc/index.md

That document looks like it does not represent what the current TSC is. For instance, it states:

>  The Technical Steering Committee (TSC) membership consists of key Collaborators who have demonstrated both technical expertise critical to the ongoing maintenance and evolution of the project and a long term commitment to driving the project and community forward.

which is _not_ what the current TSC is.

It also [links to meeting minutes of the former TSC, or rather the former Node.js' core team](https://github.com/nodejs/nodejs.org/blob/master/locale/en/foundation/tsc/index.md#technical-steering-committee-meetings).

There are other things that are out of date or incorrect in that document, it looks like it needs to be thoroughly updated.

**Comment by misterdjules** [comment]
Thank you! Landed in 6bec74c4e077060ab49eabbead8e64ce3d90fe19, I'll remove myself from the @nodejs/tsc team now, so I won't be able to make any further changes to this repository.

**Pull request closed without merging**
