### PR TITLE
Travel Fund request for @BridgeAR at Oct 2017 Collab Summit

### PR DESCRIPTION
**Pull request by BridgeAR**
Event: Collaborator's Summit at NINA 2017
Location: Vancouver, BC, CA
From: Belo Horizonte, Brazil
Amount: €1500 (approx.)

I would like to attend the Collaborator's Summit in October and to also mentor at C&L. Sadly my employer is not in a position to cover the costs, therefore I would like to ask for funding. The specified amount is an approximation, resulting from my flight from Belo Horizonte to Vancouver (prices changing daily) and lodging.

I would also love to attend the Node.js Interactive and was wondering if there is any possibility to attend that for free (covering for costs that the foundation would get back through the ticket price would be weird somehow).

### CODE REVIEW

**Comment by jasnell** [comment]
@BridgeAR ... this LGTM. Please make sure that you are [registered](https://github.com/nodejs/members)(private repo link) as an Individual Member in the Node.js Foundation.

**Comment by MylesBorins** [comment]
@BridgeAR will be great to have you around. Just to confirm, the amount you are asking for is enough to cover both a hotel and the flight?

**Comment by jasnell** [comment]
As for attending interactive, currently the travel assistance program would not cover Interactive registration tickets (correct me if I'm wrong @hackygolucky). Those would have to be covered separately.

**Comment by BridgeAR** [comment]
@jasnell thanks, I just registered. About the Interactive tickets - I am aware of that and that is why I did not added it either. I just thought it is worth asking for as I guess there might be a possibility to get free entrance?

@MylesBorins I hope so. The cheapest flights I found cost about 850 € at the moment. The main issue is the flight time that is between 21 - 40 hours with a stop in either Mexico or the US with a potentially long stay in those places. So I might need a hotel for a night in between the flights but right now I calculated it without that.

**Comment by jasnell** [comment]
As far as I know, only Speakers, Sponsors and folks directly associated with the Foundation (e.g. Board members) get free tickets... (btw, I'm checking to see if I have access to a spare one for you ...)

**Comment by BridgeAR** [comment]
@jasnell thanks a lot! :smiley: 

Uhh... seems like there is no room left in either the Metropolitan Hotel nor the Fairmont Hotel Vancouver.

**Comment by MylesBorins** [comment]
@BridgeAR you might want to check AirBnB... I noticed some rather affordable places to stay on there

One thing worth mentioning... it is not entirely clear if you need a visa to visit Canada from Brazil. I did a bit of research and found that [certain Brazilian citizens](https://www.canada.ca/en/immigration-refugees-citizenship/news/2017/04/canada_s_new_entryrulesforbrazilianbulgarianandromaniancitizens.html) can qualify for [an eTA](http://www.cic.gc.ca/english/visit/eta-start.asp?_ga=2.161617980.1417096748.1505524792-820737627.1505524792). If you don't qualify you may need a travel visa.

I am by NO means a travel attorney, but you might want to figure this out before you book anything. Let me know if I can be of any other support

**Comment by jasnell** [comment]
@BridgeAR ... Ok, looks like we've got one for you. Please send me an email so I can get you the details.

**Comment by jasnell** [comment]
Looks like there are no objections, landing!

**Pull request merged**
