### PR TITLE
update DCO to 1.1

### PR DESCRIPTION
**Pull request by williamkapke**
See #92.

### CODE REVIEW

**Comment by williamkapke** [comment]
I'm not certain that the Express application should be changed- Can someone confirm this is OK..?

**Comment by jasnell** [comment]
Yeah, I wouldn't change the Express application. That should be brought up to the express tc in an issue at http://github.com/expressjs/discussions

**Comment by williamkapke** [comment]
Ok, Express application change removed. Can I get a LGTM?

**Comment by jasnell** [comment]
LGTM

**Pull request merged**
