### PR TITLE
Add sharing TSC meeting password to onboarding

### PR DESCRIPTION
**Pull request by richardlau**

### CODE REVIEW

**Comment by richardlau** [comment]
I'm not sure if this also needs to be in the section for regular (non-voting) members, or in a new section common to both.

**Review by mhdawson — APPROVED** [review]
LGTM

**Review by tniessen — APPROVED** [review]

**Comment by aduh95** [comment]
> I'm not sure if this also needs to be in the section for regular (non-voting) members, or in a new section common to both.

I think regular members also need to have that password as they are also invited to meetings IIUC.

**Comment by tniessen** [comment]
> I'm not sure if this also needs to be in the section for regular (non-voting) members, or in a new section common to both.

AFAIK the only way to become a regular members is by being a voting member first, in which case the member already has the password.

**Review by ronag — APPROVED** [review]

**Review by MoLow — APPROVED** [review]

**Review by gireeshpunathil — APPROVED** [review]

**Review by RaisinTen — APPROVED** [review]

**Review by Trott — APPROVED** [review]

**Pull request merged**
