### PR TITLE
chore: add raw responses to rejections survey

### PR DESCRIPTION
**Pull request by mmarchini**

### CODE REVIEW

**Comment by mmarchini** [comment]
Sharing the raw data now as I'm having some trouble generating the charts I want, so if anyone else wants to take a stab at charting some extra datapoints feel free to do so.

**Comment by nschonni** [comment]
Just to see the difference, I converted it to CSV since that's more Git friendly, but the size jumps up quite a bit when converting (and losing the xlsx compression)

**Comment by mmarchini** [comment]
yeah it's a big file (2499 rows x 29 cols). I was going to convert to CSV but thought it was not worth it.

**Comment by mmarchini** [comment]
Ok, I got some charts

Leak managements vs Preferred default
App behavior vs Preferred default
Code type vs Preferred default
Use case vs Preferred default

Any other charts folks would like to see? Otherwise I'll update this PR with the charts + xls with the chart formulas

**Comment by mmarchini** [comment]
Also, if anyone has suggestions on how to show % on Google Spreadsheets in the bars alongside the numbers, I'm happy to learn :)

The tables for each chart look like this:


  | Third-party libraries | Command-line tools | Web servers | Computation-heavy processing | Desktop applications
-- | -- | -- | -- | -- | --
strict | 283 | 312 | 678 | 131 | 143
throw | 338 | 369 | 849 | 177 | 163
warn | 89 | 94 | 231 | 33 | 49
warn-with-error-code | 103 | 84 | 227 | 47 | 61
none | 18 | 23 | 43 | 12 | 16

(side note: how cool is it that GitHub will turn the table copied from Spreadsheet into Markdown 😮)

**Review by mcollina — APPROVED** [review]
lgtm

**Review by targos — APPROVED** [review]

**Review by mhdawson — APPROVED** [review]
Rubber Stamp LGTM

**Pull request merged**
