### PR TITLE
doc: add minutes for meeting Sep 9

### PR DESCRIPTION
**Pull request by mhdawson**

### CODE REVIEW

**Comment by mhdawson** [comment]
#nodejs/TSC any reviewers?

**Comment by ChALkeR** [comment]
The commit description looks incorrect — there wasn't a meeting on 2018-09-09.

**Comment by mhdawson** [comment]
@ChALkeR seems like I got that wrong, but not sure how to fix now.

**Comment by mhdawson** [comment]
The name of the file and the info in the file does match the correct date Sep 5

**Comment by ChALkeR** [comment]
@mhdawson I don't think any action is needed, as all the files themself seem correct.
But I left a comment at the commit just in case.

**Pull request merged**
