### PR TITLE
Document expectations and qualifications for TSC members.

### PR DESCRIPTION
**Pull request by mikeal**

### CODE REVIEW

**Comment by Fishrock123** [comment]
LGTM

**Comment by jasnell** [comment]
LGTM

**Comment by orangemocha** [comment]
LGTM

**Comment by jasnell** [comment]
Looks fairly uncontroversial and given the discussion yesterday during the TSC meeting I'd say let's get it landed.

**Comment by Fishrock123** [comment]
Merging, if we missed anything we can correct that later.

**Pull request merged**
