### PR TITLE
Travel Fund request for bengl @ Code & Learn @ JSConf.cn 2017

### PR DESCRIPTION
**Pull request by bengl**
Event: Code & Learn event at JSConf.cn 2017
Location: Shanghai, China
From: San Francisco, USA
Amount: US$ 1200

I'd like to reprise my role as a mentor at [Code & Learn at JSConf.cn 2017](https://github.com/nodejs/code-and-learn/issues/68), but my employer is not in a position to cover the travel costs. The amount is an estimate of flights, hotel and visa fees.

### CODE REVIEW

**Comment by jasnell** [comment]
LGTM

**Comment by indutny** [comment]
LGTM

**Comment by Trott** [comment]
@nodejs/tsc How does this work? Does this constitute approval? Or not yet?

**Comment by addaleax** [comment]
> Does this constitute approval? Or not yet?

I’m not sure we have been following a fixed rule so far … for some we’ve waited until we have a TSC majority, for others just waited a bit to see that there aren’t any objections. With 5 approvals and no objections, I’d be okay with waiting until tomorrow (so it’s been open for a week) and then saying it’s passed.

**Comment by mhdawson** [comment]
+1 to @addaleax suggestion.

**Comment by Trott** [comment]
Can @bengl consider this approved at this point?

**Comment by mhdawson** [comment]
I'd say yes.

**Pull request merged**
