### PR TITLE
doc: cover moderation of IRC, mail, and slack channels

### PR DESCRIPTION
**Pull request by jasnell**
the moderation policy currently does not explicitly cover officially supported communications channels such as IRC, Slack, Email or Conference Calls. This is a first pass at covering such channels.

/cc @nodejs/tsc

### CODE REVIEW

**Comment by Fishrock123** [comment]
The existing moderation policy does not work well for IRC for the various reasons which I have previously stated in https://github.com/nodejs/inclusivity/issues/138

**Comment by jasnell** [comment]
As I said, this is a first pass. Feel free to suggest additional edits that would improve the applicability for IRC.

**Comment by Fishrock123** [comment]
Fwiw attempting to enforce this policy on irc would be extremely impractical and I refuse to do it for #node-dev.

**Comment by jasnell** [comment]
@Fishrock123: Do you have specific recommendations on how the moderation policy can be improved to adequately cover IRC (in your opinion). Specific recommendations would be far more useful than a refusal to enforce a policy that we both agree is currently inadequate.

**Comment by Fishrock123** [comment]
An irc specific policy that includes the following (and other things I am probably forgetting):

- Who OPs are
- How to time people out (properly, including a history message)
  - Temeporary timeouts
- when to just kick people
- irc specific offences
  - such as people joining/leaving rapidly
  - excessive use of channel notifications
- how to check the access logs

**Comment by jasnell** [comment]
I will work up some proposed language based on http://nodeirc.info/, http://blog.izs.me/post/30036893703/policy-on-trolling and https://gist.github.com/maxogden/8610086 to begin addressing the IRC specific requirements.

That said, many of the same requirements likely also apply to Slack channels, and other official communications channels may also have a number of channel specific requirements. I will see what I can do to begin addressing those as well.

**Comment by Fishrock123** [comment]
Untagging until progress is made

**Comment by jasnell** [comment]
+1 .. thank you, I'd meant to do so but forgot. Appreciate it.

**Comment by jasnell** [comment]
Closing this in favor of the ongoing community work group direction.

**Pull request closed without merging**
