### PR TITLE
fix: remark-lint-no-literal-urls

### PR DESCRIPTION
**Pull request by nschonni**
- Angle bracket explicit urls
- Add mailto to email links in addition to angle brackets

### CODE REVIEW

**Comment by Trott** [comment]
https://github.com/nodejs/TSC/pull/992 deletes some content that may make this a little bit easier to review. (Or maybe not. Looks like most of the issues are in meeting notes.)

I think some of the changes here will need to land in https://github.com/nodejs/create-node-meeting-artifacts/tree/main/templates so that they don't keep showing up in meeting notes automatically and needing manual fixing.

**Comment by nschonni** [comment]
Looking at https://github.com/nodejs/create-node-meeting-artifacts/blob/main/templates/minutes_base_tsc, I can see 1 "bare link", but I'm not sure if the wrapping the things like `$MINUTES_DOC$` would break any tooling

**Comment by mhdawson** [comment]
> Looking at https://github.com/nodejs/create-node-meeting-artifacts/blob/main/templates/minutes_base_tsc, I can see 1 "bare link", but I'm not sure if the wrapping the things like $MINUTES_DOC$ would break any tooling

I'm not quite sure what your question is or what you mean by wrapping things like $MINUTES_DOC$

**Comment by nschonni** [comment]
@mhdawson sorry, the discussion kinda got mixed up between this PR and https://github.com/nodejs/create-node-meeting-artifacts/pull/103
- This PR addresses the current docs
- Trott flagged that the templates might cause the future PRs to get flagged, so I opened that other one.
- In the other PR I didn't wrap any of the variables in the templates like `$MINUTES_DOC$` to `<$MINUTES_DOC$>` since I didn't dig into the tool to see if that would cause issues

**Comment by Trott** [comment]
@nschonni Can you rebase?

**Comment by mhdawson** [comment]
@nschonni question a bit unrelated to this specific PR. Is it possible to omit running the linter on the directory with the meeting minutes?

**Comment by nschonni** [comment]
The glob could probably be changed. I think for a few of those small ones that tripped up your other PR, EditorConfig in your IDE would probably fix all the trailing space nits. The indentation ones also sometime catch lists that GitHub won't render right

**Review by Trott — APPROVED** [review]
Rubber-stamp LGTM

**Comment by mhdawson** [comment]
@nschonni I'm asking because as one of the people who handles a good part of minutes which, the extra work versus the benefit is at question.  Right now I have a low overhead flow that just pulls down the google doc, I do some small editing and then submit the PR. If I have to then update the PR every time due to the linter it will effectively double the work, and I'm not sure how much value it addes.

**Comment by mhdawson** [comment]
@nschonni I guess a good question is if there is a command line that could be run as part of pulling down the file that would fix all of the things the linter is complaining about automatically?

**Comment by nschonni** [comment]
@mhdawson I believe `remark-lint` has an `-o` in the CLI to overwrite the formatting, but I think it might do some other things to lists if I remember. To be honest, I think most of my fixups have been done using `markdownlint --fix "**/*"`, which might be another option if you want to include that as a fixup in whatever your local automation setup is

**Review by mhdawson — APPROVED** [review]
LGTM

**Pull request merged**
