### PR TITLE
decharter Ecosystem Security Working Group

### PR DESCRIPTION
**Pull request by Trott**
It seems that the working group can function as a GitHub team.

Closes: https://github.com/nodejs/TSC/issues/1081

### CODE REVIEW

**Comment by Trott** [comment]
@nodejs/tsc @nodejs/security-wg

**Review by joyeecheung — APPROVED** [review]
It seems there are a fair bit of drive-by fixes above the deleted lines?

**Comment by Trott** [comment]
> It seems there are a fair bit of drive-by fixes above the deleted lines?

Yes. I can remove them and put them in a separate PR if that's preferable.

**Comment by mcollina** [comment]
I think so. By their charter the security working group is responsible for keeping the node cves up-to-date. However, this is now done by the security steward.

**Review by RafaelGSS — APPROVED** [review]

**Review by DanielRuf — APPROVED** [review]

**Review by UlisesGascon — APPROVED** [review]

**Pull request merged**
