### PR TITLE
add minutes for March 21 2018 meeting

### PR DESCRIPTION
**Pull request by Trott**
Someone please add the link to the recording.

If you have any small and likely-uncontroversial fixes, please commit them directly to the branch. (I find editing the PR in the GitHub interface is convenient for these things.)

### CODE REVIEW

**Comment by TimothyGu** [comment]
Recording URL: https://www.youtube.com/watch?v=pJ9Fs_qMuZQ

Not in the GitHub org yet so can't edit.

**Comment by WaleedAshraf** [comment]
@Trott I see all latest meeting notes are in `TSC/meetings/` but this one is in `TSC/meetings/node.js/`
Not sure, but is there a specific reason? 

We are trying to define one pattern for all meeting notes in https://github.com/nodejs/community-committee/issues/267

**Comment by Trott** [comment]
> @Trott I see all latest meeting notes are in TSC/meetings/ but this one is in TSC/meetings/node.js/
Not sure, but is there a specific reason?

A mistake because the directory layout in this repo is confusing, I guess.

**Comment by Trott** [comment]
> @Trott I see all latest meeting notes are in TSC/meetings/ but this one is in TSC/meetings/node.js/
Not sure, but is there a specific reason?

I'm not sure I understand why meeting notes are in three places in this repo. The ones in the meetings/io.js directory, I get. But the ones in meetings/node.js and the ones in meetings, can't tell you what the difference is.

**Comment by Trott** [comment]
(Probably a good idea to PR moving all the ones out of meetings/node.js and into meetings. But I don't think that should hold up this landing.)

**Comment by Trott** [comment]
Oh, I think I get it now! I think meetings/io.js and meetings/node.js are both pre-merge, but everything in meetings is post-merge?

Just added a commit to this PR to move stuff to the right place, since it's just this and one other file.

**Comment by WaleedAshraf** [comment]
I think you are right about pre-merge.
Well, we are all set now. 👍👍

**Pull request merged**
