### PR TITLE
chore: update YAML files to comply with core lint requirements

### PR DESCRIPTION
**Pull request by Trott**
Make the YAML files comply with the requirements of `make lint-yaml` in
the core repo.

### CODE REVIEW

**Review by apapirovski — APPROVED** [review]

**Review by RaisinTen — COMMENTED** [review]
Shouldn't we enable the linter first and then change the code to comply with its rules in order to prevent future changes from undoing your change (though not intentionally)?

**Comment by Trott** [comment]
> Shouldn't we enable the linter first and then change the code to comply with its rules in order to prevent future changes from undoing your change (though not intentionally)?

We'd need a job to [install the Python linter](https://github.com/nodejs/node/blob/154fa4132b0dfc23c2776960a7c2d2d5d7f4e59d/Makefile#L1497-L1501), retrieve the [yamllint.yaml file from the main repo](https://github.com/nodejs/node/blob/HEAD/.yamllint.yaml), and then [run the linter](https://github.com/nodejs/node/blob/154fa4132b0dfc23c2776960a7c2d2d5d7f4e59d/Makefile#L1506).

**Comment by Trott** [comment]
> We'd need a job to [install the Python linter](https://github.com/nodejs/node/blob/154fa4132b0dfc23c2776960a7c2d2d5d7f4e59d/Makefile#L1497-L1501), retrieve the [yamllint.yaml file from the main repo](https://github.com/nodejs/node/blob/HEAD/.yamllint.yaml), and then [run the linter](https://github.com/nodejs/node/blob/154fa4132b0dfc23c2776960a7c2d2d5d7f4e59d/Makefile#L1506).

Although I guess it's possible that yamllint is installed already on the GitHub Actions images. I haven't checked.....

**Comment by Trott** [comment]
> Although I guess it's possible that yamllint is installed already on the GitHub Actions images. I haven't checked.....

Looks like yamllint is indeed already installed. So all that needs to happen is to get the yamllint config file from the core repo.

**Comment by Trott** [comment]
There we go. OK, this now includes enabling yamllint. Please take a look. @RaisinTen

**Review by RaisinTen — APPROVED** [review]
Thanks, looks good! :)

**Pull request merged**
