### PR TITLE
Remove orangemocha from TSC members

### PR DESCRIPTION
**Pull request by orangemocha**
Update TSC member list following orangemocha's resignation.

### CODE REVIEW

**Comment by williamkapke** [comment]
Sry to see you go- Thanks for everything!

Changes are correct.

**Comment by williamkapke** [comment]
Also, this list will need to be re-syncd with the website:
https://github.com/nodejs/nodejs.org/blob/master/locale/en/foundation/tsc/index.md

**Comment by jasnell** [comment]
Reluctant LGTM

**Comment by orangemocha** [comment]
Someone else will have to land this, as I don't have the commit bit anymore. Thank you.

**Pull request merged**
