### PR TITLE
chore: add vote data for automatic collaborator move-to-emeritus

### PR DESCRIPTION
**Pull request by Trott**
Refs: https://github.com/nodejs/node/pull/41155

### CODE REVIEW

**Review by richardlau — APPROVED** [review]

**Review by mhdawson — APPROVED** [review]
LGTM

**Review by cjihrig — CHANGES_REQUESTED** [review]
It was not clear to me that this was a vote. Apparently [I wasn't the only one](https://github.com/nodejs/node/pull/41155#issuecomment-995039849).

**Comment by Trott** [comment]
> It was not clear to me that this was a vote. Apparently [I wasn't the only one](https://github.com/nodejs/node/pull/41155#issuecomment-995039849).

It wasn't officially, but I figure that erring on the side of considering "waiting for a majority of TSC to approve" type things TSC votes is preferable. The TSC Charter puts the baseline for TSC participation as participating in one vote in a three month period, so the more things that are considered votes, the easier it is to meet that requirement. Non-participation in a vote is not penalized, so counting more things as votes doesn't hurt anyone. That's not the case for meetings, where there is a percentage attendance threshold.

If you still think this shouldn't land, I won't argue and will close it.

**Comment by cjihrig** [comment]
> Non-participation in a vote is not penalized, so counting more things as votes doesn't hurt anyone.

I think it's a very unlikely scenario, but couldn't this technically become the only vote in a 3 month period?

I won't block this, but I really think we should be more explicit moving forward about what constitutes a vote since it can technically impact someone.

**Comment by Trott** [comment]
> I think it's a very unlikely scenario, but couldn't this technically become the only vote in a 3 month period?

Sure but in that case, leaving this out so that there are *no* votes in a 3-month period would mean that only attendance at meetings matters. Adding a vote in would make it easier to meet the either/or requirement of vote or attendance. With no votes, you have to be attending the meetings or else you don't meet the requirements.

**Comment by Trott** [comment]
> I won't block this, 

I'm going to close this. It wasn't a vote strictly speaking and I don't want to do something that can be questioned/debated if there's a -0 in the mix. 

> but I really think we should be more explicit moving forward about what constitutes a vote

I can't argue with that.

**Comment by targos** [comment]
I assumed a change to the governance document required a vote but I'm probably wrong

**Comment by Trott** [comment]
> I assumed a change to the governance document required a vote but I'm probably wrong

The usual consensus process is sufficient. We can't change the TSC charter that way,  but governance of Node.js repo is ordinary decision-making.

We could choose to either informally agree or formally require that such changes go through a TSC vote.

**Pull request closed without merging**
